---
abstract: 'a virtual browser that retries errors with AnyEvent'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-HTTP-LWP-UserAgent-Determined
requires:
  AnyEvent::HTTP::LWP::UserAgent: 0.08
  LWP: 0
version: 0.01.1.06
